### YamlMime:ModuleUnit
uid: learn.wwl.use-azure-cosmos-db-sql-api-sd.5-configure-connectivity-mode

title: Configure connectivity mode
metadata:
  title: Configure connectivity mode
  description: "Configure connectivity mode"
  ms.date: 10/23/2024
  author: wwlpublish
  ms.author: calopez
  ms.topic: unit
azureSandbox: false
labModal: false
durationInMinutes: 7
content: |
  [!include[](includes/6-configure-connectivity-mode.md)]
